### ISSUE TITLE
Bump up to new SDK (3.3) - causing issues?

### ISSUE THREAD

**Issue by jlooper** [EddyVerbruggen/nativescript-plugin-firebase-demo#1]
When simply cloning this repo and following the instructions, I get the following error. Note, I'm on 0.39.0 cocoapods version, per our understanding that this is needed. Is there some old version of Firebase that I should uninstall? Yikes!

```
LOOPERMAC:Firebase Looper$ tns run ios --emulator
Executing before-prepare hook from /Users/Looper/Desktop/nativescript-plugin-firebase-demo-master/Firebase/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
Failed to find LaunchScreen.storyboard but it was specified in the Info.plist.
Consider updating the resources in app/App_Resources/iOS/.
A good starting point would be to create a new project and diff the changes with your current one.
Also the following repo may be helpful: https://github.com/NativeScript/template-hello-world/tree/master/App_Resources/iOS
We will now place an empty obsolete compatability white screen LauncScreen.xib for you in platforms/ios/Firebase/Resources/LaunchScreen.xib so your app may appear as it did in pre v2.1.0 versions of the ios runtime.
The iOS Deployment Target is now 8.0 in order to support Cocoa Touch Frameworks in CocoaPods.
Successfully prepared plugin nativescript-plugin-firebase for ios.
Successfully prepared plugin tns-core-modules for ios.
The iOS Deployment Target is now 8.0 in order to support Cocoa Touch Frameworks.
Successfully prepared plugin tns-core-modules-widgets for ios.
Installing pods...
Updating local specs repositories

CocoaPods 1.0.1 is available.
To update use: `gem install cocoapods`
Until we reach version 1.0 the features of CocoaPods can and will change.
We strongly recommend that you use the latest version at all times.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Firebase/Database (~> 3.3)` required by `Podfile`
Processing node_modules failed. Error: Command sandbox-pod failed with exit code 1 Error output: 
 [!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0`

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

Sending exception report (press Ctrl+C to stop).....
```

**Comment by jlooper** [comment]
Putting the solution here, in case of problems for others! 

You need to get rid of any older installation of a Firebase SDK on your system before you can install a new one. Normally to do this, you can go to /platforms/ios and hit `pod repo update --verbose`. For me, this was failing because there were some rogue, untracked pods in my /Specs folder. 

Using the --verbose flag, you can see which ones they are, and remove them manually:
For me they were:

```
Updating spec repo `master`
  $ /usr/local/bin/git pull --ff-only
  error: The following untracked working tree files would be overwritten by merge:
    Specs/JLCustomImagesViewerView/1.0.0/JLCustomImagesViewerView.podspec.json
    Specs/PJFDataSource/1.0.0/PJFDataSource.podspec.json
    Specs/Spotify-iOS-SDK/0.16.1/Spotify-iOS-SDK.podspec.json
  Please move or remove them before you can merge.
  Aborting
  Updating 3c20e73..89624d8
```

Once I removed these folders, I hit `pod install` and the entire repo is updated via Git, installing Firebase 3.3.0. 

Hope this will help others.

**Comment by EddyVerbruggen** [comment]
@jlooper Do you feel like this is something for the readme? I'm a little hesitant since this can happen to any pod-powered plugin..

**Comment by l4u532** [comment]
So far no luck with the proposed solution... Installs Firebase 2.4.3 nonetheless.

Here's my procedure:

- clone firebase branch `git clone -b firebase https://github.com/NativeScript/sample-Groceries.git`
- set remote to https://github.com/NativeScript/sample-Groceries/
- `git checkout firebase`
- `tns build ios`
- navigate into platforms/ios
- `pod repo update --verbose`
> Updating spec repo `master`
>   $ /usr/bin/git pull --ff-only
>   From https://github.com/CocoaPods/Specs
>      4e5870a..50059fb  master     -> origin/master
>   Updating 4e5870a..50059fb
>   Fast-forward
>    .../1.6.0-beta5/CommonUtils.podspec.json           | 72 ++++++++++++++++++++++
>    1 file changed, 72 insertions(+)
>    create mode 100644 Specs/CommonUtils/1.6.0-beta5/CommonUtils.podspec.json

- `pod install` **installs Firebase 2.4.3**:

> pod install
> Analyzing dependencies
> Downloading dependencies
> Using Firebase (2.4.3)
> Generating Pods project
> Integrating client project
> Sending stats
> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
> 
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `sampleGroceries` to `Pods/Target Support Files/Pods-sampleGroceries/Pods-sampleGroceries.debug.xcconfig` or include the `Pods/Target Support Files/Pods-sampleGroceries/Pods-sampleGroceries.debug.xcconfig` in your build configuration (`sampleGroceries/build-debug.xcconfig`).
> 
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `sampleGroceries` to `Pods/Target Support Files/Pods-sampleGroceries/Pods-sampleGroceries.release.xcconfig` or include the `Pods/Target Support Files/Pods-sampleGroceries/Pods-sampleGroceries.release.xcconfig` in your build configuration (`sampleGroceries/build-release.xcconfig`).

**Comment by l4u532** [comment]
OK

- `pod install firebase`
- change podfile to include

> pod 'Firebase/Core'
> pod 'Firebase/Database', '~> 3.2'
> pod 'Firebase/Auth', '~> 3.2'

- `pod update`

- running emulator now gives me the error described as above:

> [!] Unable to satisfy the following requirements:
> 
> - `Firebase (~> 2.4.3)` required by `Podfile`

- `pod repo update --verbose `does the following

> Updating spec repo `master`
>   $ /usr/bin/git pull --ff-only
>   From https://github.com/CocoaPods/Specs
>      7344e21..76154f6  master     -> origin/master
>   Updating 7344e21..76154f6
>   Fast-forward
>    .../SwiftIconFont/2.3.0/SwiftIconFont.podspec.json | 24 ++++++++++++++++++++++
>    1 file changed, 24 insertions(+)
>    create mode 100644 Specs/SwiftIconFont/2.3.0/SwiftIconFont.podspec.json

- `pod install` spits out the following error

> Analyzing dependencies
> [!] Unable to satisfy the following requirements:
> 
> - `Firebase (~> 2.4.3)` required by `Podfile`
> 
> Specs satisfying the `Firebase (~> 2.4.3)` dependency were found, but they required a higher minimum deployment target.

**Comment by l4u532** [comment]
- Found this in
sample-Groceries/node_modules/nativescript-plugin-firebase/platforms/ios/Podfile:
`    1: pod 'Firebase', '~> 2.4.3'`

- Changed it to
```
pod 'Firebase/Core'
pod 'Firebase/Database', '~> 3.2'
pod 'Firebase/Auth', '~> 3.2'
```
- `tns run ios` now works, but...

- but when clicking signin/signup
`** BUILD SUCCEEDED **

Project successfully built.
Using  /Users/5p4ck0/Dropbox/NativeScript/sample-Groceries/platforms/ios/build/emulator/sampleGroceries.app
Starting iOS Simulator
Jul 10 13:46:32 14u53Rs-MacBook-Air backboardd[13030]: SecTaskCopyDebugDescription: sampleGroceries[13084]
Jul 10 13:46:32 14u53Rs-MacBook-Air backboardd[13030]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Jul 10 13:46:32 14u53Rs-MacBook-Air backboardd[13030]: SecTaskCopyDebugDescription: sampleGroceries[13084]
Jul 10 13:46:32 14u53Rs-MacBook-Air backboardd[13030]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Jul 10 13:46:32 14u53Rs-MacBook-Air backboardd[13030]: SecTaskCopyDebugDescription: sampleGroceries[13084]
Jul 10 13:46:32 14u53Rs-MacBook-Air backboardd[13030]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Jul 10 13:46:32 14u53Rs-MacBook-Air backboardd[13030]: SecTaskCopyDebugDescription: sampleGroceries[13084]
Jul 10 13:46:32 14u53Rs-MacBook-Air backboardd[13030]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
Jul 10 13:46:32 14u53Rs-MacBook-Air backboardd[13030]: SecTaskCopyDebugDescription: sampleGroceries[13084]
Jul 10 13:46:33 14u53Rs-MacBook-Air sampleGroceries[13084]: assertion failed: 15E65 13E230: libxpc.dylib + 71506 [6F98A9DA-B46E-3A2B-88D4-92F1EC77477F]: 0x7d
Jul 10 13:46:34 14u53Rs-MacBook-Air sampleGroceries[13084]: CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:61:18: Error in firebase.init: ReferenceError: Can't find variable: Firebase
Jul 10 13:46:34 14u53Rs-MacBook-Air sampleGroceries[13084]: CONSOLE LOG file:///app/shared/view-models/user-view-model.js:23:28: firebase.init error: ReferenceError: Can't find variable: Firebase
Jul 10 13:47:42 14u53Rs-MacBook-Air sampleGroceries[13084]: CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:97:18: Error in firebase.login: ReferenceError: Can't find variable: instance
Jul 10 13:47:42 14u53Rs-MacBook-Air sampleGroceries[13084]: -[__NSDictionaryI length]: unrecognized selector sent to instance 0x7c158b20
Jul 10 13:47:43 14u53Rs-MacBook-Air sampleGroceries[13084]: *** JavaScript call stack:
	(
		0   UIApplicationMain@[native code]
		1   start@file:///app/tns_modules/application/application.js:233:26
		2   anonymous@file:///app/app.js:3:24
		3   evaluate@[native code]
		4   moduleEvaluation@:1:11
		5   @:8:48
		6   promiseReactionJob@:1:11
	)
Jul 10 13:47:43 14u53Rs-MacBook-Air sampleGroceries[13084]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryI length]: unrecognized selector sent to instance 0x7c158b20'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x04323494 __exceptionPreprocess + 180
		1   libobjc.A.dylib                     0x03ddde02 objc_exception_throw + 50
		2   CoreFoundation                      0x0432d253 -[NSObject(NSObject) doesNotRecognizeSelector:] + 275
		3   CoreFoundation                      0x0426289d ___forwarding___ + 1037
		4   CoreFoundation                      0x0426246e _CF_forwarding_prep_0 + 14
		5   UIKit                               0x02a1b52d -[UILabel _ensureBaselineMetricsReturningBounds] + 143
		6   UIKit                               0x02a1b78d -[UILabel _firstBaselineOffsetFromTop] + 46
		7   UIKit                               0x0316f5be -[UIView(AdditionalLayoutSupport) _baselineOffsetFromNearestEdgeForLayoutAttribute:] + 61
		8   UIKit                               0x03171054 -[UIView(AdditionalLayoutSupport) nsli_lowerAttribute:intoExpression:withCoefficient:forConstraint:onBehalfOfLayoutGuide:] + 1426
		9   UIKit                               0x03170aad -[UIView(AdditionalLayoutSupport) nsli_lowerAttribute:intoExpression:withCoefficient:forConstraint:] + 86
		10  Foundation                          0x02324650 lower_1_attribute + 194
		11  Foundation                          0x023240c2 -[NSLayoutConstraint _lowerIntoExpression:reportingConstantIsRounded:] + 99
		12  Foundation                          0x02319422 -[NSLayoutConstraint _addToEngine:integralizationAdjustment:mutuallyExclusiveConstraints:] + 97
		13  Foundation                          0x02323ec6 -[NSLayoutConstraint _addToEngine:] + 56
		14  UIKit                               0x0316cc46 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 568
		15  Foundation                          0x02328440 -[NSISEngine withBehaviors:performModifications:] + 150
		16  Foundation                          0x0232b91c -[NSISEngine withAutomaticOptimizationDisabled:] + 48
		17  UIKit                               0x0316d0e8 -[UIView(AdditionalLayoutSupport) _withAutomaticEngineOptimizationDisabledIfEngineExists:] + 75
		18  UIKit                               0x0316c9bc __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 741
		19  UIKit                               0x0316d0f0 -[UIView(AdditionalLayoutSupport) _withAutomaticEngineOptimizationDisabledIfEngineExists:] + 83
		20  UIKit                               0x0316c682 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 248
		21  UIKit                               0x0316c585 -[UIView(AdditionalLayoutSupport) _parentalLayoutEngineDidChangeTo:] + 55
		22  UIKit                               0x0316cb07 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 249
		23  Foundation                          0x02328440 -[NSISEngine withBehaviors:performModifications:] + 150
		24  Foundation                          0x0232b91c -[NSISEngine withAutomaticOptimizationDisabled:] + 48
		25  UIKit                               0x0316d0e8 -[UIView(AdditionalLayoutSupport) _withAutomaticEngineOptimizationDisabledIfEngineExists:] + 75
		26  UIKit                               0x0316c9bc __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 741
		27  UIKit                               0x0316d0f0 -[UIView(AdditionalLayoutSupport) _withAutomaticEngineOptimizationDisabledIfEngineExists:] + 83
		28  UIKit                               0x0316c682 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 248
		29  UIKit                               0x02831de4 -[UIScrollView _switchToLayoutEngine:] + 107
		30  UIKit                               0x0316c585 -[UIView(AdditionalLayoutSupport) _parentalLayoutEngineDidChangeTo:] + 55
		31  UIKit                               0x0316cb07 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 249
		32  Foundation                          0x02328440 -[NSISEngine withBehaviors:performModifications:] + 150
		33  Foundation                          0x0232b91c -[NSISEngine withAutomaticOptimizationDisabled:] + 48
		34  UIKit                               0x0316d0e8 -[UIView(AdditionalLayoutSupport) _withAutomaticEngineOptimizationDisabledIfEngineExists:] + 75
		35  UIKit                               0x0316c9bc __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 741
		36  UIKit                               0x0316d0f0 -[UIView(AdditionalLayoutSupport) _withAutomaticEngineOptimizationDisabledIfEngineExists:] + 83
		37  UIKit                               0x0316c682 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 248
		38  UIKit                               0x0316c585 -[UIView(AdditionalLayoutSupport) _parentalLayoutEngineDidChangeTo:] + 55
		39  UIKit                               0x0316cb07 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 249
		40  Foundation                          0x02328440 -[NSISEngine withBehaviors:performModifications:] + 150
		41  Foundation                          0x0232b91c -[NSISEngine withAutomaticOptimizationDisabled:] + 48
		42  UIKit                               0x0316d0e8 -[UIView(AdditionalLayoutSupport) _withAutomaticEngineOptimizationDisabledIfEngineExists:] + 75
		43  UIKit                               0x0316c9bc __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 741
		44  UIKit                               0x0316d0f0 -[UIView(AdditionalLayoutSupport) _withAutomaticEngineOptimizationDisabledIfEngineExists:] + 83
		45  UIKit                               0x0316c682 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 248
		46  UIKit                               0x0316c585 -[UIView(AdditionalLayoutSupport) _parentalLayoutEngineDidChangeTo:] + 55
		47  UIKit                               0x0316cb07 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 249
		48  Foundation                          0x02328440 -[NSISEngine withBehaviors:performModifications:] + 150
		49  Foundation                          0x0232b91c -[NSISEngine withAutomaticOptimizationDisabled:] + 48
		50  UIKit                               0x0316d0e8 -[UIView(AdditionalLayoutSupport) _withAutomaticEngineOptimizationDisabledIfEngineExists:] + 75
		51  UIKit                               0x0316c9bc __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 741
		52  UIKit                               0x0316d0f0 -[UIView(AdditionalLayoutSupport) _withAutomaticEngineOptimizationDisabledIfEngineExists:] + 83
		53  UIKit                               0x0316c682 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 248
		54  UIKit                               0x0316c585 -[UIView(AdditionalLayoutSupport) _parentalLayoutEngineDidChangeTo:] + 55
		55  UIKit                               0x0316cb07 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 249
		56  Foundation                          0x02328440 -[NSISEngine withBehaviors:performModifications:] + 150
		57  Foundation                          0x0232b91c -[NSISEngine withAutomaticOptimizationDisabled:] + 48
		58  UIKit                               0x0316d0e8 -[UIView(AdditionalLayoutSupport) _withAutomaticEngineOptimizationDisabledIfEngineExists:] + 75
		59  UIKit                               0x0316c9bc __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 741
		60  UIKit                               0x0316d0f0 -[UIView(AdditionalLayoutSupport) _withAutomaticEngineOptimizationDisabledIfEngineExists:] + 83
		61  UIKit                               0x0316c682 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 248
		62  UIKit                               0x0316c585 -[UIView(AdditionalLayoutSupport) _parentalLayoutEngineDidChangeTo:] + 55
		63  UIKit                               0x02813db6 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_blockJul 10 13:47:43 14u53Rs-MacBook-Air com.apple.CoreSimulator.SimDevice.2AEDDD37-810F-493E-A555-491B10B4B94D.launchd_sim[13011] (UIKitApplication:org.nativescript.groceries[0xc07c][13084]): Service exited due to signal: Abort trap: 6`

**Comment by l4u532** [comment]
- Tried removing the platform folder and then adding it again with `tns add platform ios`
and adding my google-services.plist as proposed under https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/63
- also updated config.js to represent my own Firebase account
**- still no success**

**Comment by jlooper** [comment]
I'm going to post it to my personal blog, no worries
