### ISSUE TITLE
email login error

### ISSUE THREAD

**Issue by gbonline** [EddyVerbruggen/nativescript-plugin-firebase-demo#6]
Hi, I've just tried this demo but when I try the login with email/password I get the following error:
`CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:1193:18: Error in firebase.login: ReferenceError: Can't find variable: FIREmailAuthProvider`

**Comment by EddyVerbruggen** [comment]
I have _just_ updated the plugin and the demo and that's one of the things the update underying Pod changed. Make sure you do a `pod repo update`, clone this repo again, and run the demo again.
