### ISSUE TITLE
email login error

### ISSUE THREAD

**Issue by gbonline** [EddyVerbruggen/nativescript-plugin-firebase-demo#7]
As wrote before, the error still appear,
I've tried the command `pod repo update` everywhere: inside the Firebase folder, outside it, and on my project folder, every time I've cloned the project demo and the error still present.
On my iOS app, I've tried the `tns plugin update` command, but nothing changed .
What else can I try?

**Comment by EddyVerbruggen** [comment]
What exact steps did you take? From an empty local folder to the error please.

Also, make sure when looking at the very first `tns run ios` during your steps that the Firebase Pod that's being downloaded is 4.x, not 3.x.

**Comment by gbonline** [comment]
I' simply clone this repo `git clone https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo.git nativescript-plugin-firebase-demo-master`

`cd nativescript-plugin-firebase-demo-master/Firebase`

then
`tns run ios`

The firebase plugin showed on tree  is 4.0.0
the build is succesfully

the app open on ios simulator, then init and email login

**Comment by EddyVerbruggen** [comment]
Thx, I'll take a look.

**Comment by EddyVerbruggen** [comment]
Looks like my hunch is correct - the Firebase pod is 3.x, not 4.x. Need to investigate this..

<img width="353" alt="screen shot 2017-06-20 at 18 42 11" src="https://user-images.githubusercontent.com/1426370/27344919-526a0be8-55e8-11e7-917a-0ac1545fb463.png">

**Comment by gbonline** [comment]
maybe here ?

`/**
 * Create the iOS PodFile for installing the Firebase iOS dependencies and service dependencies
 *
 * @param {any} result The answers to the micro-service prompts
 */
function writePodFile(result) {
    if(!fs.existsSync(directories.ios)) {
        fs.mkdirSync(directories.ios);
    }
    try {
        fs.writeFileSync(directories.ios + '/Podfile',
`pod 'Firebase', '~> 3.17.0'
pod 'Firebase/Database'
pod 'Firebase/Auth'

# Uncomment if you want to enable Remote Config
` + (isSelected(result.remote_config) ? `` : `#`) + `pod 'Firebase/RemoteConfig'

# Uncomment if you want to enable Crash Reporting
` + (isSelected(result.crash_reporting) ? `` : `#`) + `pod 'Firebase/Crash'

# Uncomment if you want to enable FCM (Firebase Cloud Messaging)
` + (isSelected(result.messaging) ? `` : `#`) + `pod 'Firebase/Messaging'

# Uncomment if you want to enable Firebase Storage
` + (isSelected(result.storage) ? `` : `#`) + `pod 'Firebase/Storage'

# Uncomment if you want to enable AdMob
` + (isSelected(result.admob) ? `` : `#`) + `pod 'Firebase/AdMob'

# Uncomment if you want to enable Invites
` + (isSelected(result.invites) ? `` : `#`) + `pod 'Firebase/Invites'

# Uncomment if you want to enable Facebook Authentication
` + (isSelected(result.facebook_auth) ? `` : `#`) + `pod 'FBSDKCoreKit'
` + (isSelected(result.facebook_auth) ? `` : `#`) + `pod 'FBSDKLoginKit'

# Uncomment if you want to enable Google Authentication
` + (isSelected(result.google_auth) ? `` : `#`) + `pod 'GoogleSignIn'`);
        console.log('Successfully created iOS (Pod) file.');
    } catch(e) {
        console.log('Failed to create iOS (Pod) file.');
        console.log(e);
    }
}
`

**Comment by gbonline** [comment]
Found!
I've changed the version in the Podfile in the platform/ios folder of the plugin !

**Comment by EddyVerbruggen** [comment]
Yes, sadly the Podfile in the plugin was correct, but [the installer wasn't fully updated](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/commit/6d1c06d4de460571943bd3e9969ddc835dca32a7). It is now.

4.0.1 has the fix, and this demo has also been updated.

Thanks for flagging this!
